from flask import Flask, request, jsonify
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
import random

app = Flask(__name__)

# Sample complaint lists (replace these with your actual complaints)
road_complaints = [
    "There is a massive pothole in the middle of the road near my house, causing traffic jams.",
    "The road near the railway station is broken and needs immediate repair.",
    "There are multiple potholes on the main road near the market. It's becoming dangerous.",
    "The road near my office has a deep crack that's causing vehicles to swerve.",
    "The road near the bus stop is broken, causing delays in public transport.",
    "There is a large pothole on the road near the school entrance, which is unsafe for students.",
    "A section of the road near the shopping mall has completely broken down.",
    "The road near the hospital is damaged, making it difficult for ambulances to pass.",
    "The road near the park has a massive pothole that has not been fixed for weeks.",
    "There is a broken road near the bus terminal that's becoming a traffic hazard.",
    "The main road near the river has started to break up, causing problems for trucks.",
    "The road near the university is in poor condition, with large cracks and potholes.",
    "There is a dangerous pothole near the police station that hasn't been repaired in months.",
    "The road near the train station is filled with holes, making it unsafe for vehicles.",
    "A major section of the highway near the airport is completely broken down.",
    "The road near the shopping center has deep cracks that are causing accidents.",
    "There is a large hole in the road near the bridge, causing cars to swerve.",
    "The road near the stadium is broken and needs to be fixed immediately.",
    "A portion of the road near the cinema is badly damaged and dangerous.",
    "The road near the grocery store has a massive crack that's causing traffic delays.",
    "There are potholes near the police headquarters that need urgent repairs.",
    "The road near the library has large holes that are damaging vehicles.",
    "The road near the restaurant is deteriorating quickly, and it's unsafe.",
    "There are deep cracks on the road near the university campus, which need attention.",
    "The road near the airport is broken down, and it's causing a major bottleneck.",
    "There is a pothole on the road near the beach that needs to be repaired urgently.",
    "The road near the city park is in bad condition, causing accidents.",
    "The broken section of the road near the construction site is unsafe for vehicles.",
    "There are several potholes near the town hall that are worsening each day.",
    "The road near the supermarket is falling apart and needs to be fixed immediately.",
    "The road near the fire station is badly damaged, making it difficult for fire trucks.",
    "There is a large hole on the road near the school crossing, causing danger for children.",
    "The road near the community center is full of potholes, which are causing delays.",
    "The road near the hospital is broken down, and it’s a challenge for patients to reach.",
    "The road near the bus stand is falling apart, and traffic jams are frequent.",
    "There is a section of the road near the train platform that is seriously damaged.",
    "The road near the stadium parking lot is broken, making it hard for visitors.",
    "The road near the bus stop has been deteriorating for months, with no repairs.",
    "The road near the police station is cracked, making it difficult for police vehicles.",
    "There are deep potholes on the road near the public park, causing safety concerns.",
    "A section of the road near the zoo is falling apart and needs urgent repairs.",
    "There are cracks on the road near the sports complex that need to be fixed.",
    "The road near the town square is broken, creating problems for pedestrians and vehicles.",
    "A major pothole near the hospital entrance has caused several accidents.",
    "The road near the train station is damaged, making it dangerous for travelers.",
    "The road near the stadium is filled with cracks and potholes, and it's unsafe.",
    "There are several potholes on the road near the bakery, causing delays for drivers.",
    "A section of the road near the grocery shop is completely broken, causing issues.",
    "The road near the university campus has several deep cracks and needs repair.",
    "There is a large pothole on the road near the bridge that is causing problems for drivers.",
    "The road near the airport parking lot is falling apart, making it dangerous for visitors.",
    "The road near the fountain is broken, and it's making the area unsafe for tourists.",
    "There are several potholes near the post office that need to be repaired.",
    "The road near the school is falling apart, and it’s causing safety risks for students.",
    "There is a major crack in the road near the shopping mall that is worsening.",
    "The road near the library has large holes that are causing inconvenience for commuters.",
    "The road near the community park has a broken section that needs immediate attention.",
    "The road near the concert hall is full of cracks, and it’s unsafe for visitors.",
    "The road near the sports stadium is broken, causing traffic congestion.",
    "There is a pothole near the train station that needs immediate repair.",
    "The road near the zoo entrance is damaged, creating traffic jams and delays.",
    "A section of the road near the bank is broken, making it unsafe for customers.",
    "The road near the police headquarters is cracked and needs urgent repairs.",
    "The road near the town hall is full of potholes that need to be fixed immediately.",
    "The road near the museum is in poor condition and needs to be resurfaced.",
    "There is a deep pothole near the industrial zone that is damaging trucks.",
    "The road near the cinema is full of cracks and needs to be fixed.",
    "There is a broken section of the road near the university that is causing traffic issues.",
    "The road near the city park has several potholes, which are creating safety hazards.",
    "A section of the road near the railway station is broken down, causing delays.",
    "The road near the stadium is deteriorating, causing issues for commuters.",
    "The road near the sports complex is full of potholes, creating safety risks for drivers.",
    "The road near the school has several deep cracks that need urgent attention.",
    "A section of the road near the bank is broken and unsafe for vehicles.",
    "There is a large pothole on the road near the bakery that is causing traffic delays.",
    "The road near the train platform is damaged, and it’s dangerous for travelers.",
    "The road near the bus terminal is full of potholes, making it difficult to drive.",
    "The road near the grocery store is falling apart, and it's unsafe for pedestrians.",
    "There are large cracks on the road near the supermarket, causing traffic delays.",
    "The road near the bus stop has a broken section that needs immediate repair.",
    "The road near the church parking lot is damaged, causing traffic jams.",
    "The road near the police station is cracked, and it needs urgent repairs.",
    "The road near the post office is full of potholes, and it’s causing delays.",
    "There are several cracks on the road near the stadium parking lot that need fixing.",
    "The road near the shopping mall is in poor condition, with large potholes.",
    "There is a deep pothole near the fire station that needs immediate repair.",
    "The road near the school crossing is dangerous due to deep cracks.",
    "The road near the library is damaged, making it difficult for people to walk.",
    "A pothole near the restaurant parking lot is causing damage to vehicles.",
    "There is a large pothole near the office complex that needs urgent attention.",
    "The road near the city park is cracked and dangerous for cyclists.",
    "The road near the bus terminal is falling apart, causing traffic issues.",
    "There are deep potholes near the police headquarters that need fixing.",
    "A section of the road near the grocery shop is broken, causing traffic delays.",
    "The road near the stadium is in bad condition, and it needs to be resurfaced.",
    "The road near the school bus stop is full of potholes, making it unsafe for children.",
    "A large pothole near the park entrance is causing problems for pedestrians.",
    "The road near the railway station is deteriorating and needs to be fixed urgently.",
    "The road near the university library is filled with potholes, causing accidents.",
    "There is a pothole near the office parking lot that is damaging cars.",
    "The road near the town hall is full of cracks and potholes, making it dangerous.",
    "There is a pothole near the bus stand that is creating traffic issues.",
    "The road near the fire station is damaged, causing delays for emergency vehicles.",
    "The road near the community center is full of cracks, making it difficult to drive.",
    "There is a large pothole near the supermarket that needs immediate repair.",
    "The road near the cinema is full of potholes, causing accidents.",
    "The road near the church is cracked and in need of repair.",
    "The road near the university entrance is full of potholes and cracks.",
    "There is a broken section of the road near the bus stop.",
    "The road near the stadium parking lot is in poor condition, creating safety hazards.",
    "A large pothole near the post office is causing problems for pedestrians.",
    "The road near the public park is damaged, and it’s unsafe for people.",
    "The road near the school parking lot is falling apart, causing traffic jams.",
    "The road near the zoo is full of potholes that need urgent attention.",
    "There is a pothole near the shopping mall that is making traffic difficult.",
    "The road near the restaurant is full of cracks, causing safety concerns.",
    "A section of the road near the university library is broken.",
    "There is a pothole near the bakery that is causing problems for drivers.",
    "The road near the stadium parking lot is cracked and in bad condition.",
    "The road near the police station is broken, and it’s a traffic hazard.",
    "A large pothole near the hospital entrance is making it difficult for patients.",
    "There is a pothole near the cinema parking lot that needs to be repaired.",
    "The road near the train station is broken and needs to be resurfaced.",
    "The road near the airport parking lot is full of potholes.",
    "There are large cracks in the road near the stadium entrance.",
    "The road near the town square is damaged and needs to be fixed.",
    "A pothole near the grocery shop is causing traffic issues.",
    "There are cracks on the road near the bus terminal that need to be repaired.",
    "The road near the zoo entrance is in poor condition, with cracks and potholes.",
    "The road near the library is damaged, and it’s unsafe for pedestrians.",
    "There is a broken section of the road near the office complex.",
    "The road near the public garden has several cracks that need attention.",
    "A pothole near the restaurant parking lot is creating issues.",
    "The road near the fire station is full of potholes, making it difficult for fire trucks.",
    "There is a large crack in the road near the university.",
    "The road near the community park is in poor condition, and it needs to be resurfaced.",
    "There are cracks on the road near the cinema that need to be repaired.",
    "The road near the city park is full of potholes, causing traffic delays.",
    "There is a pothole near the post office that is causing trouble for vehicles.",
    "The road near the police headquarters is broken and needs to be fixed.",
    "There are deep potholes near the supermarket that need attention.",
    "The road near the restaurant is full of potholes, making it difficult to drive.",
    "A section of the road near the train station is cracked and needs repair.",
    "The road near the community center is in poor condition, with cracks and potholes.",
    "The road near the library is damaged and needs to be resurfaced.",
    "There is a pothole near the airport parking lot that is creating problems.",
    "The road near the zoo is in bad condition, with cracks and potholes.",
    "The road near the university is broken and in need of immediate attention.",
    "A pothole near the bus stop is causing traffic congestion.",
    "The road near the sports stadium is full of cracks and potholes.",
    "There is a large crack on the road near the bank.",
    "The road near the supermarket is damaged, creating safety risks for pedestrians.",
    "There is a pothole near the restaurant parking lot that needs fixing.",
    "The road near the police station is full of potholes and cracks.",
    "A broken section of the road near the university is causing traffic problems.",
    "There are deep potholes near the zoo entrance that need urgent repairs.",
    "The road near the stadium parking lot is full of cracks that need to be fixed.",
    "The road near the town hall is broken down, causing traffic jams.",
    "There is a large pothole near the bakery that needs immediate attention.",
    "A section of the road near the university campus is deteriorating.",
    "The road near the school entrance is damaged, making it difficult for students.",
    "The road near the police station is falling apart, creating safety issues.",
    "There is a broken section of the road near the bus stop.",
    "The road near the train station is full of potholes and needs to be resurfaced.",
    "There is a deep pothole near the public garden.",
    "The road near the supermarket is in bad condition.",
    "A section of the road near the police station is cracked.",
    "There are cracks in the road near the university campus.",
    "The road near the stadium is deteriorating, causing safety risks.",
    "The road near the train station is full of potholes.",
    "The road near the city park is in bad condition.",
    "There is a pothole near the town hall that needs fixing.",
    "A section of the road near the bus terminal is broken.",
    "The road near the supermarket is cracked and damaged.",
    "There are several potholes near the police headquarters.",
    "The road near the university campus is deteriorating.",
    "The road near the fire station is cracked and needs repairs.",
    "The road near the library is full of potholes.",
    "A pothole near the school is creating traffic delays.",
    "The road near the bus stand is broken down.",
    "There are deep cracks on the road near the supermarket.",
    "The road near the cinema is in poor condition.",
    "The road near the hospital entrance needs urgent repairs.",
    "There is a large pothole near the university that needs attention.",
    "The road near the train station is broken.",
    "There is a crack in the road near the police station.",
    "The road near the town square is deteriorating.",
    "There are several cracks on the road near the community park.",
    "The road near the sports complex is damaged.",
    "The road near the university library is deteriorating.",
    "The road near the post office is full of cracks.",
    "A pothole near the sports stadium is creating traffic delays.",
    "There is a broken section of the road near the community center.",
    "The road near the public park is in bad condition.",
    "The road near the school crossing is cracked.",
    "There are cracks on the road near the university entrance.",
    "The road near the supermarket is damaged.",
    "The road near the community center is full of potholes.",
    "A pothole near the post office is causing issues for vehicles.",
    "The road near the cinema is filled with cracks.",
    "The road near the hospital entrance is deteriorating.",
    "There is a large pothole near the community park.",
    "The road near the stadium is cracked.",
    "A section of the road near the sports stadium is falling apart.",
    "The road near the zoo is broken down.",
    "The road near the police station is in poor condition.",
    "The road near the shopping mall is damaged.",
    "There is a large pothole near the fire station.",
    "The road near the library is cracked and needs repairs.",
    "A pothole near the university is causing delays.",
    "The road near the bank is full of cracks.",
    "There is a broken section of the road near the park.",
    "The road near the supermarket is deteriorating.",
    "A section of the road near the town hall is damaged.",
    "The road near the stadium parking lot is full of potholes.",
    "There is a deep crack on the road near the public garden.",
    "The road near the zoo entrance needs repairs.",
    "There is a pothole near the office complex that needs to be fixed.",
    "A section of the road near the police station is deteriorating.",
    "The road near the community center is full of potholes.",
    "There is a pothole near the zoo that needs to be repaired.",
    "The road near the stadium is in bad condition.",
    "The road near the cinema is full of cracks.",
    "A section of the road near the university is damaged.",
    "There is a large pothole near the restaurant.",
    "The road near the shopping mall is broken.",
    "There is a pothole near the community park.",
    "The road near the school bus stop is cracked.",
    "The road near the train station is broken.",
    "There are potholes near the police headquarters.",
    "The road near the school crossing is in bad condition.",
    "There is a large crack on the road near the cinema.",
    "The road near the supermarket is filled with potholes.",
    "The road near the stadium parking lot is damaged.",
    "The road near the bus stop is cracked.",
    "There are deep cracks on the road near the zoo.",
    "The road near the post office is deteriorating.",
    "There is a broken section of the road near the public park.",
    "The road near the library is in poor condition.",
    "There is a large pothole near the police station.",
    "The road near the hospital is filled with cracks.",
    "There is a pothole near the zoo that needs to be fixed.",
    "The road near the restaurant is broken down.",
    "A large crack near the stadium parking lot needs repairs.",
    "The road near the stadium is deteriorating.",
    "The road near the post office is damaged.",
    "There are large potholes on the road near the university.",
    "There is a broken section of the road near the sports complex.",
    "The road near the supermarket is cracked and filled with potholes.",
    "There is a deep pothole near the community park.",
]

# Sewage Department (Leaking sewage, Open sewage)
sewage_complaints = [
    "There is sewage leaking on the road near my house, causing a foul smell.",
    "The open sewage near the park has created a health hazard for people.",
    "The sewage drain near the school is leaking, and it needs urgent attention.",
    "Sewage is leaking from a manhole near the grocery store.",
    "The open sewage near the train station is creating a serious sanitation issue.",
    "There is a strong smell of sewage near the hospital entrance.",
    "The sewage drain near the town square has a leak that’s spreading all over.",
    "Open sewage near the cinema complex is making it unsafe for visitors.",
    "Sewage water is leaking from the drain near the police station.",
    "There is an open sewage problem near the university that’s spreading everywhere.",
    "Sewage is leaking from the manhole near the bus terminal.",
    "The sewage near the community center is open, and it’s creating a risk for children.",
    "There’s a sewage leak near the stadium parking lot.",
    "Open sewage near the fire station is making it unsafe for emergency vehicles.",
    "The sewage system near the shopping mall has a leak.",
    "Sewage is leaking into the storm drain near the zoo entrance.",
    "There’s an open sewage problem near the grocery store that needs fixing.",
    "The sewage system near the school is leaking and is causing a health issue.",
    "The sewage near the sports complex is leaking and needs immediate repairs.",
    "There is an open sewage issue near the library that needs to be fixed.",
    "The sewage near the town hall is leaking and needs attention.",
    "The sewage near the train station has caused flooding on the road.",
    "There is a sewage leak near the police headquarters that’s causing a smell.",
    "Sewage is overflowing from the drain near the university campus.",
    "There is an open sewage problem near the post office.",
    "The sewage near the stadium is leaking into the road.",
    "There’s an open sewage issue near the public park.",
    "The sewage near the cinema is leaking, and it needs immediate repairs.",
    "Sewage is spilling out of a manhole near the fire station.",
    "The sewage system near the hospital is leaking and causing health concerns.",
    "There is open sewage near the police station.",
    "The sewage near the community park is leaking, creating a health risk.",
    "There’s an open sewage issue near the shopping center.",
    "Sewage is leaking near the university, making it a sanitation hazard.",
    "There is an open sewage issue near the school entrance.",
    "Sewage is leaking near the bus terminal and creating a foul smell.",
    "There’s an open sewage issue near the town hall.",
    "Sewage near the zoo is overflowing and creating problems for visitors.",
    "The sewage near the library is leaking, creating a hazard for pedestrians.",
    "There’s an open sewage problem near the stadium that needs to be addressed.",
    "Sewage is leaking near the fire station, making it unsafe for emergency vehicles.",
    "The sewage near the supermarket is leaking and needs urgent repairs.",
    "There is an open sewage issue near the post office that’s causing a risk.",
    "The sewage near the concert hall is leaking and causing a problem.",
    "There’s an open sewage problem near the shopping mall.",
    "Sewage is leaking near the school crossing.",
    "There is an open sewage issue near the restaurant.",
    "The sewage near the train station has created a health risk.",
    "There is a sewage leak near the bus stop.",
    "The sewage near the zoo entrance is leaking and needs to be fixed.",
    "Sewage is overflowing near the community center.",
    "The sewage near the stadium parking lot is leaking.",
    "Sewage is leaking near the sports stadium.",
    "The sewage near the police headquarters is overflowing.",
    "There is a sewage problem near the town hall.",
    "The sewage near the fire station is leaking, creating a mess.",
    "Sewage is leaking near the bus terminal.",
    "The sewage near the university campus is overflowing.",
    "Sewage is spilling near the school entrance.",
    "The sewage near the grocery shop is leaking and spreading.",
    "There is a sewage issue near the public garden.",
    "Sewage is leaking near the community park.",
    "The sewage near the police station is overflowing.",
    "Sewage is leaking near the stadium parking lot.",
    "There is an open sewage issue near the post office.",
    "Sewage is leaking near the library.",
    "The sewage near the train station is overflowing.",
    "There is an open sewage problem near the town hall.",
    "The sewage near the supermarket is leaking.",
    "Sewage is spilling near the cinema.",
    "The sewage near the police headquarters is leaking.",
    "There is a sewage leak near the university.",
    "Sewage is leaking near the concert hall.",
    "The sewage near the community park is overflowing.",
    "Sewage is leaking near the school crossing.",
    "There is an open sewage issue near the school entrance.",
    "The sewage near the fire station is leaking and creating a risk.",
    "Sewage is leaking near the university campus.",
    "There is an open sewage issue near the shopping mall.",
    "Sewage is overflowing near the police station.",
    "The sewage near the restaurant is leaking.",
    "Sewage is leaking near the zoo entrance.",
    "There is an open sewage problem near the public park.",
    "Sewage is overflowing near the stadium.",
    "The sewage near the sports complex is leaking.",
    "There is an open sewage issue near the post office.",
    "The sewage near the supermarket is leaking.",
    "Sewage is leaking near the concert hall.",
    "There is a sewage leak near the bus stop.",
    "The sewage near the university is overflowing.",
    "Sewage is spilling near the shopping mall.",
    "There is a broken sewage drain near the zoo.",
    "Sewage is overflowing near the university.",
    "There is an open sewage issue near the police station.",
]

# Street Light Department (Light not working, Flickering lights)
street_light_complaints = [
    "The street light near my house is not working and it’s unsafe at night.",
    "There is a flickering street light near the park entrance that needs fixing.",
    "The street lights on the main road near the bus station are not working.",
    "The street light near the school is broken, making the area dark and unsafe.",
    "There is a flickering light near the town square that needs to be repaired.",
    "The street light near the police station is not working.",
    "There is a faulty street light near the grocery store that’s causing visibility issues.",
    "The street lights along the highway near the train station are malfunctioning.",
    "The street light near the community center is flickering and needs repair.",
    "The street light near the bus terminal is broken, making it difficult to see at night.",
    "There is a broken street light near the stadium entrance.",
    "The street light near the zoo entrance is not working.",
    "The street light near the university campus is flickering.",
    "There is a street light near the hospital entrance that’s not functioning.",
    "The street light near the post office is broken.",
    "The street light near the fire station is not working, making it dark for vehicles.",
    "The street lights near the concert hall are flickering.",
    "There is a malfunctioning street light near the school crossing.",
    "The street lights near the supermarket are out.",
    "There is a broken street light near the town hall.",
    "The street light near the bus stop is flickering.",
    "There is a broken street light near the stadium parking lot.",
    "The street light near the police headquarters is not working.",
    "The street light near the community park is not functioning.",
    "The street light near the cinema is broken.",
    "There is a flickering street light near the restaurant entrance.",
    "The street light near the library is not working.",
    "The street light near the bank is broken.",
    "The street light near the sports stadium is flickering.",
    "There is a malfunctioning street light near the university library.",
    "The street light near the shopping mall is not working.",
    "There is a broken street light near the train station platform.",
    "The street light near the post office is flickering.",
    "The street light near the stadium is not functioning.",
    "The street light near the sports complex is broken.",
    "There is a flickering street light near the town hall.",
    "The street light near the zoo is broken.",
    "The street light near the restaurant is flickering.",
    "There is a malfunctioning street light near the police station.",
    "The street light near the public park is not working.",
    "There is a broken street light near the bus stand.",
    "The street light near the cinema complex is flickering.",
    "There is a malfunctioning street light near the school.",
    "The street light near the community center is out.",
    "The street light near the stadium is flickering.",
    "There is a broken street light near the library entrance.",
    "The street light near the fire station is flickering.",
    "The street light near the concert hall is not working.",
    "The street light near the post office is out.",
    "There is a flickering street light near the town square.",
    "The street light near the supermarket is broken.",
    "There is a broken street light near the police headquarters.",
    "The street light near the train station is flickering.",
    "The street light near the stadium entrance is not working.",
    "There is a malfunctioning street light near the zoo entrance.",
    "The street light near the school crossing is broken.",
    "The street light near the sports complex is flickering.",
    "There is a flickering street light near the bus stop.",
    "The street light near the bank is not functioning.",
    "The street light near the community park is flickering.",
    "There is a broken street light near the university campus.",
    "The street light near the shopping mall is flickering.",
    "The street light near the police station is broken.",
    "There is a broken street light near the town hall.",
    "The street light near the library is flickering.",
    "There is a street light near the fire station that is not working.",
    "The street light near the zoo is malfunctioning.",
    "There is a flickering street light near the restaurant.",
    "The street light near the university is broken.",
    "The street light near the stadium parking lot is malfunctioning.",
    "There is a broken street light near the post office.",
    "The street light near the community center is flickering.",
    "The street light near the bus stop is malfunctioning.",
    "There is a broken street light near the school crossing.",
]

# Waste Management Department (Waste on road, Uncollected waste)
waste_management_complaints = [
    "There is uncollected waste on the road near my house, attracting pests.",
    "The waste on the street near the park has been piling up for days.",
    "Garbage is left uncollected on the road near the bus stop, creating a mess.",
    "There’s a large pile of waste on the road near the grocery store that needs collection.",
    "The street near the hospital is covered with garbage, causing a sanitation issue.",
    "Uncollected waste near the train station is creating a bad smell.",
    "There’s a large pile of garbage near the university campus that has not been cleared.",
    "Waste is being dumped near the stadium, and it’s creating an eyesore.",
    "There’s uncollected trash near the police station, making the area look untidy.",
    "Garbage has been left near the community center for several days.",
    "There is a pile of uncollected waste near the shopping mall entrance.",
    "The waste near the fire station is left uncollected and is attracting stray animals.",
    "There is waste on the road near the zoo that’s creating a nuisance for visitors.",
    "Uncollected waste near the cinema is making it difficult for people to walk safely.",
    "The area near the town hall has been filled with garbage for weeks.",
    "There is a large pile of waste near the bus terminal that needs urgent removal.",
    "Garbage is overflowing on the streets near the school, creating a health hazard.",
    "Uncollected waste near the post office is making the area look neglected.",
    "There’s uncollected trash near the concert hall that needs to be cleared.",
    "The street near the supermarket is cluttered with trash that’s been left for days.",
    "Garbage near the fire station is overflowing and causing a stench.",
    "There is waste scattered on the street near the stadium parking lot.",
    "Uncollected trash near the community park is attracting rats.",
    "There is garbage on the road near the university that needs to be picked up.",
    "Waste has been piling up near the restaurant, creating a sanitation issue.",
    "There is uncollected waste on the road near the school crossing.",
    "Trash has been left on the road near the police headquarters.",
    "There’s a pile of garbage near the public park that’s creating a smell.",
    "Uncollected waste near the town square is attracting flies and other pests.",
    "There’s uncollected trash on the street near the stadium.",
    "The street near the library has garbage scattered everywhere.",
    "There’s a heap of waste on the road near the fire station that’s been there for days.",
    "Garbage is being dumped on the street near the cinema complex.",
    "Uncollected waste near the zoo entrance is creating problems for visitors.",
    "The street near the university is littered with garbage that’s been there for too long.",
    "There’s uncollected waste near the concert hall that’s creating an eyesore.",
    "The area near the bus stop is filled with trash and needs cleaning.",
    "There is a large amount of uncollected waste near the shopping center.",
    "Garbage has been left near the police station for several days.",
    "Uncollected trash near the school entrance is causing inconvenience to students.",
    "There’s uncollected garbage near the supermarket that needs immediate removal.",
    "There’s a pile of trash near the stadium entrance that’s making the area look dirty.",
    "Waste on the road near the town hall is spreading and causing a health concern.",
    "There’s a significant amount of uncollected waste near the community center.",
    "Trash near the police headquarters is overflowing, making the area unsightly.",
    "There is garbage on the road near the post office that has been left for days.",
    "Uncollected waste near the zoo entrance is attracting stray animals.",
    "Garbage has been left near the library for several days, creating a nuisance.",
    "There’s a pile of uncollected waste near the stadium that needs immediate removal.",
    "Uncollected trash near the bus terminal is making the area unwelcoming.",
    "There’s an enormous pile of garbage near the school crossing.",
    "Waste is scattered across the street near the supermarket and needs to be collected.",
    "Garbage near the concert hall is making the area appear neglected.",
    "There’s an issue with uncollected waste near the train station platform.",
    "The street near the town hall is littered with garbage and needs cleaning.",
    "Uncollected trash near the university campus is creating a sanitation hazard.",
    "The street near the grocery store is filled with trash and needs to be cleared.",
    "There’s a pile of waste near the stadium parking lot that’s causing a stink.",
    "Garbage has been left near the police station, making the area unsanitary.",
    "Uncollected waste near the fire station is attracting stray animals.",
    "There’s a large pile of trash near the public park that needs to be removed.",
    "The area near the library is filled with garbage and needs immediate attention.",
    "Garbage has been left on the road near the shopping mall for several days.",
    "Uncollected waste near the community center is creating a health risk.",
    "There is trash all over the street near the zoo, which needs urgent removal.",
]

complaints = []
labels = []

for _ in range(1000):
    complaints.append(random.choice(road_complaints))
    labels.append("Road Department")
    complaints.append(random.choice(waste_management_complaints))
    labels.append("Waste Management Department")
    complaints.append(random.choice(sewage_complaints))
    labels.append("Sewage Department")
    complaints.append(random.choice(street_light_complaints))
    labels.append("Street Light Department")

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(complaints)  # Convert text data into TF-IDF features

y = labels


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)



def predict_department(input_description):
    
    input_tfidf = vectorizer.transform([input_description])

    
    predicted_department = nb_model.predict(input_tfidf)

    return predicted_department[0]



@app.route("/predict", methods=["POST"])
def predict():
    data = request.get_json()
    input_description = data.get("description")

    if not input_description:
        return jsonify({"error": "No description provided"}), 400

    predicted_department = predict_department(input_description)
    return jsonify({"predicted_department": predicted_department})


if __name__ == "__main__":
    app.run(debug=True)
